name: Sync upstream & Call build

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
  workflow_dispatch:
    inputs:
      specific_folder:
        description: "Enter specific folder"
        required: true
        default: "DIY"
        type: string

env:
  repo_upstream: ophub/amlogic-s9xxx-openwrt
  specific_folder: ${{ inputs.specific_folder || 'DIY' }}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      actions: write
    steps:
      - name: Set Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Checkout source repo
        uses: actions/checkout@main
        with:
          token: ${{ secrets.PAT }}

      - name: Sync and merge upstream changes
        id: upstream
        working-directory: ${{ github.workspace }}
        run: |
          git remote add upstream https://github.com/${{ env.repo_upstream }}
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories --strategy-option theirs

      - name: Overwrite specific folder
        id: overwrite
        working-directory: ${{ github.workspace }}
        run: |
          cp -rf ./${{ env.specific_folder }}/* ./
          ls -R ./

      - name: Check and commit changes
        id: check_and_commit
        working-directory: ${{ github.workspace }}
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Sync Upstream and Overwrite Files"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}"
          branch: ${{ github.ref }}
          directory: ${{ github.workspace }}

      - name: Clear workspace
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf ./* 2>/dev/null
          df -hT ${PWD}

  diy:
    needs: sync
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      actions: write
    steps:
      - name: Set Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Checkout source repo
        uses: actions/checkout@main
        with:
          token: ${{ secrets.PAT }}

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Generate DIY Workflow
        working-directory: ${{ github.workspace }}
        env:
          SOURCE_FILE: ${{ github.workspace }}/.github/workflows/build-openwrt.yml
          TARGET_FILE: ${{ github.workspace }}/.github/workflows/DIY-build-openwrt.yml
        run: |
          cp ${{ env.SOURCE_FILE }} ${{ env.TARGET_FILE }}
          sed -i -r 's/^name: .*/name: DIY Build OpenWrt/g' ${{ env.TARGET_FILE }}
          sed -i '/- name: Upload the packaged OpenWrt/ i \
                - name: Remove date from file names\
                  working-directory: \$\{\{ env.PACKAGED_OUTPUTPATH \}\}\
                  run: |\
                    sudo apt-get update\
                    sudo apt-get install -y rename\
                    rename "s/_[0-9]{4}.[0-9]{2}.[0-9]{2}//g" *.img.gz*\n' ${{ env.TARGET_FILE }}
          cat ${{ env.TARGET_FILE }}
          ls -R ${{ github.workspace }}/.github/workflows

      - name: Check and commit changes
        id: commit
        working-directory: ${{ github.workspace }}
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "DIY files"
            echo "status=success" >> ${GITHUB_OUTPUT}
          fi

      - name: Push changes
        id: push
        if: steps.commit.outputs.status == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}"
          branch: ${{ github.ref }}
          directory: ${{ github.workspace }}

      - name: Clear workspace
        id: clearwork
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf ./* 2>/dev/null
          df -hT ${PWD}
          echo "status=success" >> ${GITHUB_OUTPUT}

  call-build:
    needs: diy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    strategy:
      matrix:
        openwrt_kernel: ["6.6.y", "6.1.y"]
      fail-fast: false
      max-parallel: 2
    steps:
      - name: Trigger workflow - Build OpenWrt
        id: trigger
        env:
          workflow_target: DIY-build-openwrt.yml
        run: |
          data='
          {
            "ref": "main",
            "inputs": {
              "source_branch": "openwrt-main",
              "openwrt_board": "s905d",
              "openwrt_kernel": "${{ matrix.openwrt_kernel }}",
              "auto_kernel": "true",
              "kernel_repo": "ophub/kernel",
              "kernel_usage": "stable",
              "openwrt_storage": "save",
              "builder_name": "yourname"
            }
          }'
          curl -XPOST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.workflow_target }}/dispatches \
          --data "$data"
