name: Sync Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  # push:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      specific_folder:
        description: "Enter specific folder"
        required: true
        default: "DIY"
        type: string

env:
  specific_folder: ${{ inputs.specific_folder || 'DIY' }}

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: aormsby/Fork-Sync-With-Upstream-action@main
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: ophub/amlogic-s9xxx-openwrt

      # - name: Checkout upstream repo
      #   uses: actions/checkout@main
      #   with:
      #     repository: ophub/amlogic-s9xxx-openwrt
      #     fetch-depth: 1
      #     path: upstream

      - name: Checkout source repo
        uses: actions/checkout@main
        with:
          repository: Grinch27/amlogic-s9xxx-openwrt
          # fetch-depth: 1
          # path: source

      - name: Copy files
        run: |
          # cp -rf ${{ github.workspace }}/source/${{ env.specific_folder }}/* ${{ github.workspace }}/upstream/
          cp -rf ${{ github.workspace }}/${{ env.specific_folder }}/* ${{ github.workspace }}/

      - name: Commit and push changes
        run: |
          cd ${{ github.workspace }}
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Sync Upstream and Overwrite Files"
          # git push

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: ${{ github.workspace }}
# jobs:
#   call-build:
#     uses: ophub/amlogic-s9xxx-openwrt/.github/workflows/build-openwrt.yml@main
#     with:
#       target: stage
