name: Sync upstream & Call build

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
  workflow_dispatch:
    inputs:
      specific_folder:
        description: "Enter specific folder"
        required: true
        default: "DIY"
        type: string

env:
  specific_folder: ${{ inputs.specific_folder || 'DIY' }}

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout source repo
        id: source
        uses: actions/checkout@main

      - name: Sync upstream changes
        id: upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@main
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: ophub/amlogic-s9xxx-openwrt

      - name: Checkout source repo
        uses: actions/checkout@main

      - name: Copy files
        id: copy
        run: |
          # cp -rf ${{ github.workspace }}/source/${{ env.specific_folder }}/* ${{ github.workspace }}/upstream/
          cp -rf ${{ github.workspace }}/${{ env.specific_folder }}/* ${{ github.workspace }}/

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet || echo "changed=true" >> ${GITHUB_OUTPUT}

      - name: Commit changes
        id: commit
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Sync Upstream and Overwrite Files"

      - name: Push changes
        id: push
        if: steps.changes.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: ${{ github.workspace }}

  call-build:
    needs: repo-sync
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Trigger Build OpenWrt workflow
        run: |
          data='
          {
            "ref": "main",
            "inputs": {
              "source_branch": "openwrt-main",
              "openwrt_board": "s905d",
              "openwrt_kernel": "6.6.y",
              "auto_kernel": "true",
              "kernel_repo": "ophub/kernel",
              "kernel_usage": "stable",
              "openwrt_storage": "save",
              "builder_name": "yourname"
            }
          }'
          curl -XPOST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-openwrt.yml/dispatches \
          --data "$data"

      # uses: ophub/amlogic-s9xxx-openwrt/.github/workflows/build-openwrt.yml@main
      # with:
      #   target: stage
